/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 doctors_stethoscope.gltf 
Author: Vera4Art (https://sketchfab.com/Elvera.Viljoen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/doctors-stethoscope-3bef1be839834f4f9ad7ff8731d90602
Title: Doctor's stethoscope
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/doctors_stethoscope.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.879, -0.627, 0]} scale={0.115}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/doctors_stethoscope.gltf')
