/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ste2.gltf 
Author: Simon Pasi (https://sketchfab.com/simonpasi96)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rigged-stethoscope-e0d5ec7eb4c842599205c6f65b14bdd3
Title: Rigged Stethoscope
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/ste2.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_7.geometry}
          material={materials.Parts}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_9.geometry}
          material={materials.Parts}
          skeleton={nodes.Object_9.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_11.geometry}
          material={materials.Parts}
          skeleton={nodes.Object_11.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_13.geometry}
          material={materials.Parts}
          skeleton={nodes.Object_13.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_14.geometry}
          material={materials.Tube}
          skeleton={nodes.Object_14.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ste2.gltf");
