
import type { Metadata } from 'next'
import { Inter, Raleway } from 'next/font/google'
import { getServerSession } from 'next-auth';
import Link from 'next/link';
import Logout from './logout';
import '../styles/global.css'
import Provider from './Provider';
import MapPage from './components/homepage/map/page';
import HeaderPage from './components/header/page';

const raleway = Raleway({ subsets: ['latin'] })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Smile Seek',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav>
          {!!session &&
            <Logout />
          }
          {!session &&
            <Link href={'/login'}>
              Login
            </Link>
          }
        </nav> */}
        <Provider>
          <HeaderPage />
          {children}
        </Provider>
      </body>
    </html>
  )
}
