const specializations = [
    "Anestezie și Terapie Intensivă",
    "Cardiologie",
    "Chirurgie Cardiovasculară",
    "Chirurgie Generală",
    "Chirurgie Pediatrică",
    "Chirurgie Plastică și Reconstructivă",
    "Chirurgie Toracică",
    "Chirurgie Vasculară",
    "Dermatologie",
    "Endocrinologie",
    "Gastroenterologie",
    "Ginecologie și Obstetrică",
    "Hematologie",
    "Medicină de Familie",
    "Medicină Generală",
    "Medicină Internă",
    "Medicină Nucleară",
    "Medicină de Laborator",
    "Nefrologie",
    "Neurologie",
    "Oftalmologie",
    "Oncologie",
    "Ortopedie și Traumatologie",
    "Otorinolaringologie (ORL)",
    "Patologie",
    "Pediatrie",
    "Pneumologie",
    "Psihiatrie",
    "Radiologie și Imagistică Medicală",
    "Reumatologie",
    "Stomatologie",
    "Urologie"
];

export default specializations;